version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/binder"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/realms-devkit"
    schedule:
      interval: "weekly"
